### ISSUE TITLE
Train function

### ISSUE THREAD

**Issue by tvorogme** [xenx/cats-dogs_ml#2]
Don't know how to create train function for two inputs.

`train_fun = theano.function([input_X,target_y],[loss,accuracy],updates= updates_sgd)`

Need to add `input_X_new` to train function. 

You can see whole code in [two_inputs.ipynb](https://github.com/xenx/cats-dogs_ml/blob/develop/two_inputs.ipynb)

**Comment by justheuristic** [comment]
Sry, i don't seem to exactly understand what is the issue.
Your solution

```
train_fun = theano.function([input_layer.input_var,input_layer2.input_var,target_y],[loss,accuracy],updates= updates_sgd)
```

should work just fine, but it should now be called as
`train_fun(stuff_for_input_X, stuff_for_input_xnew,stuff_for_target_y)`
**in the main training loop**
So basically you just have to adapt this

```
for batch in iterate_minibatches(X_train, y_train, BATCH_SIZE):
        inputs, targets = batch
        train_err_batch, train_acc_batch= train_fun(inputs, targets)
```

(and a similar code for VALIDATION)
to correctly handle 3-input stuff whatever it is.

### Alternatively,

if input_X_new is just a vector transformation of input_X or vice versa (say, you make it grayscale), than you can do it right inside theano graph by having 1 input for X that layer undergoes two transformations, making it input_X and input_X_new respecitvely.

And, yup, sorry if i missed something.
